language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
env:
  - DJANGO=1.2.7
  - DJANGO=1.3.3
  - DJANGO=1.4.1
install:
  - pip install Django==$DJANGO --use-mirrors
  - pip install flake8 --use-mirrors
  - pip install -e . --use-mirrors
script:
  - make test
